# Generated by Django 4.2 on 2023-07-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
