# Generated by Django 4.2 on 2023-06-12 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carphoto',
            options={'verbose_name': 'Фото автомобиля', 'verbose_name_plural': 'Фото автомобиля'},
        ),
    ]
