# Generated by Django 4.2 on 2023-06-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carphoto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year_production',
            field=models.IntegerField(max_length=4, null=True, verbose_name='Год производства'),
        ),
    ]
