# Generated by Django 4.2 on 2023-06-13 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_year_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year_production',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2050)], verbose_name='Год выпуска'),
        ),
    ]
