# Generated by Django 4.2 on 2023-06-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_year_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to='cars/images', verbose_name='Фотография автомобиля'),
        ),
        migrations.DeleteModel(
            name='CarPhoto',
        ),
    ]
