# Generated by Django 4.2 on 2023-06-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_image_delete_carphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='type',
            new_name='vehicle_type',
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=20, null=True, verbose_name='Цвет'),
        ),
    ]
