# Generated by Django 4.2 on 2023-06-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_rename_type_car_vehicle_type_car_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='car',
            name='image10',
            field=models.ImageField(null=True, upload_to='cars/images', verbose_name='Фотография автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='image2',
            field=models.ImageField(null=True, upload_to='cars/images', verbose_name='Фотография автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='image3',
            field=models.ImageField(null=True, upload_to='cars/images', verbose_name='Фотография автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='image4',
            field=models.ImageField(null=True, upload_to='cars/images', verbose_name='Фотография автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='image5',
            field=models.ImageField(null=True, upload_to='cars/images', verbose_name='Фотография автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='image6',
            field=models.ImageField(null=True, upload_to='cars/images', verbose_name='Фотография автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='image7',
            field=models.ImageField(null=True, upload_to='cars/images', verbose_name='Фотография автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='image8',
            field=models.ImageField(null=True, upload_to='cars/images', verbose_name='Фотография автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='image9',
            field=models.ImageField(null=True, upload_to='cars/images', verbose_name='Фотография автомобиля'),
        ),
    ]
