# Generated by Django 4.2 on 2023-06-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_rename_image_car_image1_car_image10_car_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image9',
        ),
        migrations.AlterField(
            model_name='car',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='cars/images', verbose_name='Фотография автомобиля'),
        ),
    ]
