# Generated by Django 4.2 on 2023-06-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_car_image2_car_image3_car_image4_car_image5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image1',
            field=models.ImageField(null=True, upload_to='cars/images', verbose_name='Фотография автомобиля с правой стороны'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image2',
            field=models.ImageField(null=True, upload_to='cars/images', verbose_name='Фотография автомобиля с левой стороны'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image3',
            field=models.ImageField(null=True, upload_to='cars/images', verbose_name='Фотография автомобиля с задней стороны'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image4',
            field=models.ImageField(null=True, upload_to='cars/images', verbose_name='Фотография автомобиля с передней стороны'),
        ),
    ]
