# Generated by Django 4.2 on 2023-06-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_car_image1_alter_car_image2_alter_car_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='passport_image',
            field=models.ImageField(null=True, upload_to='cars/passport_images', verbose_name='Фотография Техпаспорта'),
        ),
    ]
