# Generated by Django 4.2 on 2023-06-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_car_last_checking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=10, null=True, verbose_name='Государственный номер автомобиля'),
        ),
    ]
